name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
change-template: '- $TITLE'
template: |
  - Notes of the previous version can be found [here](https://github.com/alejandrohdezma/.github/releases/tag/$PREVIOUS_TAG)
  $CHANGES