repository:
  has_wiki: false

  delete_branch_on_merge: true

  default_branch: master

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false

branches:
  - name: master
    protection:
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - pr-labeler
          - test