# Don't edit this file!
# It is automatically updated after every release of https://github.com/alejandrohdezma/.github
# If you want to suggest a change, please open a PR or issue in that repository

name: Update documentation

on:
  release:
    types: [published]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v7
      - name: Generate documentation
        run: sbt ci-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOWNLOAD_INFO_FROM_GITHUB: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.3
        with:
          commit_message: 'Update documentation and other files'
          branch: 'master'