name: Auto-rebase PRs

on:
  push:
    branches-ignore:
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
  pull_request:
    types: [labeled]

jobs:
  auto-rebase:
    name: Auto rebase PRs
    runs-on: ubuntu-latest
    steps:
      - uses: Label305/AutoRebase@v0.1.7
        with:
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
