name: Auto-update repositories files and secrets

on:
  repository_dispatch:
  release:
    types: [published]

jobs:
  create-pr-on-remote-repo:
    name: ${{ matrix.repo }}
    strategy:
      matrix:
        repo: [
          alejandrohdezma/sbt-codecov,
          alejandrohdezma/sbt-fix,
          alejandrohdezma/sbt-github,
          alejandrohdezma/sbt-mdoc-toc,
          alejandrohdezma/sbt-remove-test-from-pom,
          alejandrohdezma/sbt-scalafix-defaults,
          alejandrohdezma/sbt-scalafmt-defaults,
          alejandrohdezma/sensitive-strings
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to update
        uses: actions/checkout@v2
        with:
          path: main
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          repository: ${{ matrix.repo }}
      - name: Get latest release
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/:repository/releases/latest
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Parse latest release
        id: release
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.get_latest_release.outputs.data }}
          body: body
          tag_name: tag_name
      - name: Checkout latest tag
        uses: actions/checkout@v2
        with:
          path: defaults
          ref: ${{ steps.release.outputs.tag_name }}
      - name: Copy files
        run: |
          mkdir -p main/.github/workflows && cp defaults/workflows/*.yml main/.github/workflows
          mkdir -p main/.github/workflows && cp defaults/workflows/settings/*.yml main/.github
          mkdir -p main/docs && cp defaults/documentation/* main/docs
          cp -a defaults/root-files/. main
          rm -f main/.github/workflows/changelog.yml
          rm -f main/.github/workflows/update-labels.yml
          rm -f main/.github/labels.yml
      - name: Create stash with changes
        working-directory: main
        run: |
          git stash --include-untracked
          git stash apply || echo "::set-env name=NO_CHANGES::true"
      - name: Setup Scala
        if: env.NO_CHANGES == null
        uses: olafurpg/setup-scala@v7
      - name: Run checks
        if: env.NO_CHANGES == null
        working-directory: main
        run: sbt ci-test -Dskip.coverage=true || echo "::set-env name=NEEDS_PR::true"
      - name: Reset repository to auto-update changes
        if: env.NO_CHANGES == null
        working-directory: main
        run: |
          git reset --hard HEAD
          git stash pop
      - name: Push changes
        if: env.NEEDS_PR == null && env.NO_CHANGES == null
        uses: stefanzweifel/git-auto-commit-action@v4.1.3
        with:
          commit_message: Update files from `.github` to ${{ steps.release.outputs.tag_name }} [skip ci]
          repository: main
          branch: 'master'
      - name: Create Pull Request
        if: env.NEEDS_PR == 'true' && env.NO_CHANGES == null
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          path: main
          commit-message: Update actions, documentation templates and configuration files to ${{ steps.release.outputs.tag_name }}
          title: Update actions, documentation templates and configuration files to ${{ steps.release.outputs.tag_name }}
          labels: auto-update
          branch: auto-update-workflows-docs
          body: |
            > ❕This is an automated PR created from a release in [`alejandrohdezma/.github`](https://github.com/alejandrohdezma/.github).

            # What has been done in this PR?

            Update Github Actions workflows, documentation templates and configuration files to ${{ steps.release.outputs.tag_name }}.

            # Included changes

            ${{ steps.release.outputs.body }}
      - name: Show Pull Request URL
        if: env.PULL_REQUEST_NUMBER != null
        run: 'echo "Pull-request created: https://github.com/${{ matrix.repo }}/pull/${{ env.PULL_REQUEST_NUMBER }}"'
      - name: Spread settings
        uses: alejandrohdezma/repo-manager@v1
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          github-repository: ${{ matrix.repo }}
          config-file: defaults/.github/settings.yml
      - name: Spread secrets
        uses: google/secrets-sync-action@v1.1.3
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        with:
          secrets: |
            ^ADMIN_GITHUB_TOKEN$
            ^PGP.*
            ^SONATYPE.*
          repositories: |
            ${{ matrix.repo }}
          github_token: ${{ secrets.SPREAD_SECRETS_GITHUB_TOKEN }}
