name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-scala-steward:
    runs-on: ubuntu-latest
    name: Run `sbt fix generateCiFiles` in Scala Steward PRs
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'alejandrohdezma' && contains(github.event.pull_request.body, 'Scala Steward')
    outputs:
      changes_detected: ${{ steps.push.outputs.changes_detected }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Coursier
        uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:1.11
          apps: sbt
      - name: Enable Coursier cache
        uses: coursier/cache-action@v6
      - name: Check if `.github/auto_assign.yml` exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".github/auto_assign.yml"
      - name: Add Pull Request Reviewer
        if: steps.check_files.outputs.files_exists == 'true'
        uses: kentaro-m/auto-assign-action@v1.1.2
      - run: sbt generateCiFiles fix || sbt "generateCiFiles; scalafmtAll; scalafmtSbt" || true
      - name: Push changes
        id: push
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: Regenerate files with `sbt generateCiFiles fix`
  post-scala-steward:
    runs-on: ubuntu-latest
    name: Auto-merge succesfull Scala Steward PRs
    needs: [test]
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'alejandrohdezma' && contains(github.event.pull_request.body, 'Scala Steward')
    steps:
      - name: Automerge Scala Steward PRs
        uses: ridedott/merge-me-action@v2.2.21
        with:
          GITHUB_LOGIN: alejandrohdezma
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  test:
    needs: [pre-scala-steward]
    if: always() && !contains(github.event.head_commit.message, 'skip ci') && needs.pre-scala-steward.outputs.changes_detected != 'true'
    name: Run "sbt ci-test" on JDK ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk:
          - adopt:1.8
          - adopt:1.11
          - adopt:1.15
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.4
      - name: Setup Coursier
        uses: laughedelic/coursier-setup@v1
        with:
          jvm: ${{ matrix.jdk }}
          apps: sbt
      - name: Enable Coursier cache
        uses: coursier/cache-action@v6
      - name: Run checks
        run: sbt ci-test
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
