name: Update documentation

on:
  release:
    types: [published]
  repository_dispatch:
    types: [docs]

jobs:
  documentation:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          ref: master
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Coursier
        uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:1.8
          apps: sbt
      - name: Enable Coursier cache
        uses: coursier/cache-action@v5
      - name: Generate documentation
        run: sbt ci-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: "Update documentation [skip ci]"
